# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-08 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('change_password', 'Can change password'),), 'verbose_name': 'User', 'verbose_name_plural': 'users'},
        ),
    ]
