# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-26 12:40
from __future__ import unicode_literals

import LibraryManagementSystem.validatiors
from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('roll_no', models.CharField(max_length=32)),
                ('dob', models.DateField()),
                ('phone_no', models.CharField(max_length=15, validators=[LibraryManagementSystem.validatiors.phone_no_validation])),
                ('address', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Passed', 'Passed'), ('Droped', 'Droped')], default='Active', max_length=12)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to=students.models.get_document_filename)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('course_batch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='settings.CourseBatch')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'ordering': ['-roll_no'],
            },
        ),
    ]
