# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-07 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-roll_no'], 'permissions': (('view_student', 'Can view student'),), 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
