# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-26 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0006_remove_setting_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=16)),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('teacher', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=64)),
                ('semester', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th')], max_length=8)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('batches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='settings.Batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='settings.Course')),
            ],
        ),
    ]
