# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-27 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_auto_20190327_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
