# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-19 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('author', models.TextField(max_length=256)),
                ('edition', models.CharField(max_length=64)),
                ('publisher', models.TextField(max_length=512)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'books',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc', models.CharField(max_length=4)),
                ('status', models.CharField(max_length=64)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='book_units', to='books.Book')),
            ],
            options={
                'verbose_name': 'Book Unit',
                'verbose_name_plural': 'Book Units',
                'db_table': 'book_units',
                'ordering': ['acc'],
            },
        ),
    ]
