# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-26 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('author', models.TextField(max_length=256)),
                ('edition', models.CharField(max_length=64)),
                ('publisher', models.TextField(max_length=512)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'books',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_no', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('available', 'available'), ('pending', 'pending'), ('booked', 'booked')], default='available', max_length=64)),
                ('is_deleted', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='book_units', to='books.Book')),
            ],
            options={
                'verbose_name': 'Book Unit',
                'verbose_name_plural': 'Book Units',
                'db_table': 'book_units',
                'ordering': ['acc_no'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set([('name', 'code', 'author', 'publisher', 'edition')]),
        ),
    ]
