# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-07 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name'], 'permissions': (('can_view', 'Can view'),), 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
