# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-19 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookunit',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('pending', 'pending'), ('booked', 'booked')], default='available', max_length=64),
        ),
    ]
