# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-20 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190119_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookunit',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookunit',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookunit',
            name='remarks',
            field=models.TimeField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='bookunit',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
