# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-07 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190207_0624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name'], 'permissions': (('view_books', 'Can view books'),), 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
