# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-07 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190207_0625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name'], 'permissions': (('view_books', 'Can view books'), ('undo_book', 'Can view books')), 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='bookunit',
            options={'ordering': ['acc_no'], 'permissions': (('view_bookunit', 'Can view bookunit'), ('undo_bookunit', 'Can undo bookunit')), 'verbose_name': 'Book Unit', 'verbose_name_plural': 'Book Units'},
        ),
    ]
