# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-15 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190207_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookunit',
            options={'ordering': ['acc_no'], 'permissions': (('view_bookunit', 'Can view bookunit'), ('undo_bookunit', 'Can undo bookunit'), ('order_bookunit', 'Can order bookunit'), ('assign_bookunit', 'Can assign bookunit')), 'verbose_name': 'Book Unit', 'verbose_name_plural': 'Book Units'},
        ),
    ]
