# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-22 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20190220_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookunit',
            name='book_code',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
