# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-29 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0003_auto_20190329_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='students.Student'),
        ),
    ]
