# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-28 07:24
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='text')),
                ('title', models.TextField(max_length=512)),
                ('type', models.CharField(choices=[('', 'Select Type'), ('Notice', 'Notice'), ('Result', 'Result'), ('Syllabus', 'Syllabus')], max_length=16)),
                ('is_deleted', models.BooleanField(default=False)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'db_table': 'notices',
            },
        ),
    ]
