# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-20 09:10
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='setting',
            name='renew_days',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='setting',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
