# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-20 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20190120_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
