# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-15 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0002_auto_20190215_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrow',
            options={'ordering': ['-created_at'], 'permissions': (('view_borrow', 'Can view borrow'),), 'verbose_name': 'Borrow', 'verbose_name_plural': 'Borrows'},
        ),
    ]
