# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-20 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0004_auto_20190215_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('cancelled', 'cancelled'), ('returned', 'returned')], default='pending', max_length=32),
        ),
    ]
