# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-20 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0005_auto_20190220_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='fine',
        ),
    ]
