# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-26 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=files.models.get_document_filename)),
                ('title', models.TextField(max_length=512)),
                ('type', models.CharField(choices=[('Notice', 'Notice'), ('Result', 'Result'), ('Routine', 'Routine')], max_length=16)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'db_table': 'files',
            },
        ),
    ]
