# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-26 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'permissions': (('view_file', 'Can view file'),), 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
    ]
